### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by ultimaweapon**
See https://github.com/ultimaweapon/kyty/runs/6632324680 for the example run.

Everything went well until almost finished with the following error:

```
[ 97%] Built target emulator
Consolidate compiler generated dependencies of target fc_script
[ 97%] Linking CXX executable fc_script.exe
process_begin: CreateProcess(D:\a\kyty\kyty\__bin\fc_script.exe, ..\..\__bin\fc_script D:/a/kyty/kyty/source/map_to_csv.lua fc_script mingw 64 ld, ...) failed.
make (e=216): Error 216
mingw32-make[2]: *** [CMakeFiles\fc_script.dir\build.make:148: fc_script.exe] Error 216
mingw32-make[2]: *** Deleting file 'fc_script.exe'
mingw32-make[1]: *** [CMakeFiles\Makefile2:473: CMakeFiles/fc_script.dir/all] Error 2
mingw32-make: *** [Makefile:135: all] Error 2
```

I'm appreciate if you can point out how to fix this error. Thanks.

### CODE REVIEW

**Comment by ultimaweapon** [comment]
Okay I managed to fixes the issue and build is now succeeded. See here for the latest one https://github.com/ultimaweapon/kyty/actions/runs/2403415151

**Comment by DartPower** [comment]
Please add the (static?) libstdc++6.dll (i can't launch without this lib, which is not included in your test build)

**Comment by ultimaweapon** [comment]
Strange. I replicated the build steps from `appveyor.yml` but the artifact produced by AppVeyor has `libstdc++6.dll` but mine not.

**Comment by ultimaweapon** [comment]
Fixed. @DartPower please try the latest build here https://github.com/ultimaweapon/kyty/actions/runs/2406501681

**Pull request merged**
